Semester 4/DSR/Spotyfly/dsr_vaja1/dsr_vaja1/Controllers/IgrasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using dsr_vaja1.DAL;
using dsr_vaja1.Models.Igra;

namespace dsr_vaja1.Controllers
{
   
    public class IgrasController : Controller
    {
        private IgraContext db = new IgraContext();

        // GET: Igras
        public ActionResult Index()
        {
            return View(db.Igre.ToList());
        }

        // GET: Igras/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Igra igra = db.Igre.Find(id);
            if (igra == null)
            {
                return HttpNotFound();
            }
            return View(igra);
        }

        // GET: Igras/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View(new Igra());
        }

        // POST: Igras/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "Id,ime,proizvajalec,cena,datum_prihoda,zaloga,Zvrsti")] Igra igra)
        {
            if (ModelState.IsValid)
            {
                db.Igre.Add(igra);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(igra);
        }

        // GET: Igras/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Igra igra = db.Igre.Find(id);
            if (igra == null)
            {
                return HttpNotFound();
            }
            return View(igra);
        }

        // POST: Igras/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,ime,proizvajalec,cena,datum_prihoda,zaloga,Zvrsti")] Igra igra)
        {
            if (ModelState.IsValid)
            {
                db.Entry(igra).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(igra);
        }

        // GET: Igras/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Igra igra = db.Igre.Find(id);
            if (igra == null)
            {
                return HttpNotFound();
            }
            return View(igra);
        }

        // POST: Igras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Igra igra = db.Igre.Find(id);
            db.Igre.Remove(igra);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Semester 4/DSR/Spotyfly/dsr_vaja1/dsr_vaja1/Controllers/UporabniksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using dsr_vaja1.DAL;
using dsr_vaja1.Models.Uporabnik;

namespace dsr_vaja1.Controllers
{
    public class UporabniksController : Controller
    {
        private UporabnikContext db = new UporabnikContext();

        // GET: Uporabniks
        public ActionResult Index()
        {
            return View(db.Uporabniki.ToList());
        }

        // GET: Uporabniks/Details/5
        [Authorize(Roles ="Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uporabnik uporabnik = db.Uporabniki.Find(id);
            if (uporabnik == null)
            {
                return HttpNotFound();
            }
            return View(uporabnik);
        }


        [Authorize(Roles = "Admin")]
        // GET: Uporabniks/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uporabnik uporabnik = db.Uporabniki.Find(id);
            if (uporabnik == null)
            {
                return HttpNotFound();
            }
            return View(uporabnik);
        }

        // POST: Uporabniks/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "Id,ime,priimek,rojstni_datum,Kraji,emso,Starost,naslov,email,posta,drzava,postna_stevilka,geslo,ponovi_geslo")] Uporabnik uporabnik)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uporabnik).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(uporabnik);
        }

        // GET: Uporabniks/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uporabnik uporabnik = db.Uporabniki.Find(id);
            if (uporabnik == null)
            {
                return HttpNotFound();
            }
            return View(uporabnik);
        }

        // POST: Uporabniks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Uporabnik uporabnik = db.Uporabniki.Find(id);
            db.Uporabniki.Remove(uporabnik);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Semester 4/DSR/Spotyfly/dsr_vaja1/dsr_vaja1/Views/Shared/MasterStran.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />
   

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/mojaskripta.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>  



   

  
</head>
<body>
    
    <div class="navbar navbar-inverse navbar-static-top">
            
        <div class="container">

            @Html.ActionLink("Igre", "Index", "Igras", null, new{ @class = "navbar-brand" })
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
            
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </button>



            <div class="collapse navbar-collapse navHeaderCollapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="gumb">@Html.ActionLink("Igre","Index", "Igras")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="gumb">@Html.ActionLink("Uporabniki", "Index", "Uporabniks")</li>
                    }
              
                    <li class="gumb">
                    
                    
                    @if(User.Identity.IsAuthenticated)
                    {        
                    @Html.ActionLink("Odjava", "Logout", "Account")
                    }
                    @if (!User.Identity.IsAuthenticated)
                    {
                    @Html.ActionLink("Prijava", "Login", "Account")
                    }
                    </li>
                    
                </ul>
            </div>


        </div>
    </div>

    <div class="container">

        <div class="jumbotron">
            <center>
                <h1>Pozdravljeni v storitvi!</h1>
            </center>
        </div>
        @RenderBody()
    </div>

  
   

    <div class="navbar navbar-default navbar-fixed-bottom">

        <div class="container">

            <p class="navbar-text">Stran naredil Rene Vučko, trenutni čas:@DateTime.Now.ToString("HH:mm - dddd, d.M.yyyy", new System.Globalization.CultureInfo("en-US"))</p>
        </div>


    </div>

</body>

</html>